force-app/main/default/objects/Species__c/Species__c.object-meta.xml
<CustomObject>
    <label>Species</label>
    <nameField>
        <label>Species Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Species</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Species__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INDOORS</fullName>
            </value>
            <value>
                <fullName>OUTDOORS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SpeciesService.cls
public with sharing class SpeciesService {
    @AuraEnabled(cacheable = true)
    
    public static List<Species__c> getFilteredSpecies(String searchText){
        String likeValue = '%'+searchText+'%';
        return [
            SELECT Id, Description__c, Image_URL__c, Location__c, Name 
            FROM Species__c 
            WHERE Name LIKE : likeValue
        ];
    }

    //con esto retornamos el listado de todas species
    /*public static List<Species__c> getAllSpecies(){
        return [
            SELECT Id, Description__c, Image_URL__c, Location__c, Name 
            FROM Species__c
        ];
    }*/
}